version: "3.5"

services:
  # Jiconfi conference mapper component
  jiconfi:
    image: ijmclinden/jiconfi:${CONFERENCE_MAPPER_IMAGE_VERSION:-main}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${CONFERENCE_MAPPER_PORT:-9000}:${CONFERENCE_MAPPER_PORT:-9000}"
    volumes:
      - ${CONFIG}/jiconfi:/config:Z
      - ${CERTS}/${TLS_CERT_FILE:-cert.fullchain}:/config/keys/cert.crt
      - ${CERTS}/${TLS_KEY_FILE:-cert.key}:/config/keys/cert.key
    environment:
      - CONFERENCE_MAPPER_PHONELIST
      - CONFERENCE_MAPPER_DATABASE
      - CONFERENCE_MAPPER_PORT
      - CONFERENCE_MAPPER_ID_LENGTH
    networks:
      meet.jitsi:

networks:
  meet.jitsi:
